FROM apache/airflow:3.3.1-python3.11

COPY --chown=airflow:root requirements.txt /tmp/requirements.txt
COPY --chown=airflow:root requirements-airflow.txt /tmp/requirements-airflow.txt

RUN pip install --no-cache-dir \
    "apache-airflow==3.3.1" \
    -r /tmp/requirements.txt \
    -r /tmp/requirements-airflow.txt
